# Full stack deployment workflow - DISABLED
# This workflow includes testing and deployment
# Uncomment if you want to run tests before deployment
#
# name: Full Stack Deployment
# 
# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]
# 
# jobs:
#   test:
#     runs-on: ubuntu-latest
#     
#     steps:
#     - name: Checkout
#       uses: actions/checkout@v3
#       
#     - name: Setup Node.js
#       uses: actions/setup-node@v3
#       with:
#         node-version: '18'
#         cache: 'npm'
#         
#     - name: Install dependencies
#       run: |
#         npm install
#         cd client && npm install
#         cd ../server && npm install
#         
#     - name: Run tests (if available)
#       run: |
#         cd client && npm test -- --coverage --watchAll=false
#         cd ../server && npm test || echo "No tests found"
#         
#   deploy-frontend:
#     needs: test
#     runs-on: ubuntu-latest
#     if: github.ref == 'refs/heads/main'
#     
#     steps:
#     - name: Checkout
#       uses: actions/checkout@v3
#       
#     - name: Setup Node.js
#       uses: actions/setup-node@v3
#       with:
#         node-version: '18'
#         cache: 'npm'
#         
#     - name: Install dependencies
#       run: |
#         npm install
#         cd client && npm install
#         
#     - name: Build React app
#       run: |
#         cd client
#         npm run build
#         
#     - name: Deploy to GitHub Pages
#       uses: peaceiris/actions-gh-pages@v3
#       with:
#         github_token: ${{ secrets.GITHUB_TOKEN }}
#         publish_dir: ./client/build
#         cname: your-domain.com  # Optional: if you have a custom domain
